### PR TITLE
Fix installation issue for Python 3+

### PR DESCRIPTION
**Pull request by khorolets**
I've tried to install `django-weed` with `pip` but it has failed with:

```
File "djweed/version.py", line 2, in <genexpr>
        __version__ = '.'.join(unicode(x) for x in VERSION)
    NameError: name 'unicode' is not defined
```

I'm using Python 3.6. Here is a fix that allows to install `django-weed` on Python 3+

Are you OK with such fix?

### CODE REVIEW

**Comment by frol** [comment]
Is it the only problem? I suggest you just use `'%s.%s.%s'` instead of `join` and `unicode`.

**Comment by khorolets** [comment]
@frol This is the only problem with installation. But there is at least another one with the fresh `Django`. I can include a fix to this PR as well if you don't mind.

**Comment by frol** [comment]
Yes, please, address all the compatibility issues in a single PR.

**Comment by khorolets** [comment]
I guess I'm done. I've refactored `urls.py` because `patterns` were deprecated in Django 1.8 and now is totally removed. `django-weed` should work properly with all Django versions that are officially supported.

**Comment by frol** [comment]
Thank you!

**Comment by frol** [comment]
FYI, I have just published the 0.2.0 version on PyPi.

**Comment by khorolets** [comment]
> Thank you!

Thank you for the great project!

**Pull request merged**
